### ISSUE TITLE
Blank White pages being displayed for all extensions 

### ISSUE THREAD

**Issue by Blindsquirrelllc** [rbiddle/phppickem#8]
I followed the install instructions and see the added files to my database as well as getting the successful connection message but, when I  navigate to the signup and login pages In all of  my browsers all that is displayed is a blank white page for them what am I missing here?  any help would be appreciated.
<img width="1512" alt="Screenshot 2024-08-13 at 7 55 20 PM" src="https://github.com/user-attachments/assets/7c16b4dc-a53f-4731-9a72-a045eb720ada">

**Comment by stevenmybarra** [comment]
you're getting a white screen cause there's a fatal error. import the latest 2024-2025 schedule from the docs folder. that should fix it. but overall, everything works fine except for signing up and resetting password. let me know if it works for you.

**Comment by rbiddle** [comment]
I'll review the install code to make sure it pulls in a schedule so you have a starting point instead of a blank screen. @stevenmybarra is right though, the blank screen means an error.  If you're still hitting it, can you get the error from the log and I;ll try to help.

**Comment by Blindsquirrelllc** [comment]
thank you both,  I tried importing the schedule and was still getting errors.  I have since stopped working on this due to some other more pressing projects. hopefully I will get back to it soon.
